version: "3"
vars:
  BUILD_HASH:
    sh: git rev-parse HEAD
  BUILD_TIME:
    sh: date
  BUILD_VERSION: 0.0.1-alpha.1
tasks:
  bootstrap:
    deps:
      - update
    cmds:
      - go run build/taskfile.go
  build:
    deps:
      - build-debug
      - build-release
  build-debug:
    deps:
      - build-domino-darwin-amd64-debug
      - build-domino-darwin-amd64-release
      - build-domino-darwin-arm64-debug
      - build-domino-darwin-arm64-release
      - build-domino-linux-amd64-debug
      - build-domino-linux-amd64-release
      - build-domino-windows-amd64-debug
      - build-domino-windows-amd64-release
  build-domino-darwin-amd64-debug:
    cmds:
      - mkdir -p bin/debug
      - GOOS=darwin GOARCH=amd64 go build -gcflags="all=-N -l" -ldflags="-X 'github.com/hanselrd/domino/internal/build.Version={{.BUILD_VERSION}}' -X 'github.com/hanselrd/domino/internal/build.Time={{.BUILD_TIME}}' -X 'github.com/hanselrd/domino/internal/build.Hash={{.BUILD_HASH}}'" -o bin/debug/domino_darwin_amd64 ./cmd/domino
  build-domino-darwin-amd64-release:
    cmds:
      - mkdir -p bin/release
      - GOOS=darwin GOARCH=amd64 go build -gcflags="all=-l -B -C" -ldflags="-s -w -X 'github.com/hanselrd/domino/internal/build.Version={{.BUILD_VERSION}}' -X 'github.com/hanselrd/domino/internal/build.Time={{.BUILD_TIME}}' -X 'github.com/hanselrd/domino/internal/build.Hash={{.BUILD_HASH}}'" -o bin/release/domino_darwin_amd64 ./cmd/domino
  build-domino-darwin-arm64-debug:
    cmds:
      - mkdir -p bin/debug
      - GOOS=darwin GOARCH=arm64 go build -gcflags="all=-N -l" -ldflags="-X 'github.com/hanselrd/domino/internal/build.Version={{.BUILD_VERSION}}' -X 'github.com/hanselrd/domino/internal/build.Time={{.BUILD_TIME}}' -X 'github.com/hanselrd/domino/internal/build.Hash={{.BUILD_HASH}}'" -o bin/debug/domino_darwin_arm64 ./cmd/domino
  build-domino-darwin-arm64-release:
    cmds:
      - mkdir -p bin/release
      - GOOS=darwin GOARCH=arm64 go build -gcflags="all=-l -B -C" -ldflags="-s -w -X 'github.com/hanselrd/domino/internal/build.Version={{.BUILD_VERSION}}' -X 'github.com/hanselrd/domino/internal/build.Time={{.BUILD_TIME}}' -X 'github.com/hanselrd/domino/internal/build.Hash={{.BUILD_HASH}}'" -o bin/release/domino_darwin_arm64 ./cmd/domino
  build-domino-linux-amd64-debug:
    cmds:
      - mkdir -p bin/debug
      - GOOS=linux GOARCH=amd64 go build -gcflags="all=-N -l" -ldflags="-X 'github.com/hanselrd/domino/internal/build.Version={{.BUILD_VERSION}}' -X 'github.com/hanselrd/domino/internal/build.Time={{.BUILD_TIME}}' -X 'github.com/hanselrd/domino/internal/build.Hash={{.BUILD_HASH}}'" -o bin/debug/domino_linux_amd64 ./cmd/domino
  build-domino-linux-amd64-release:
    cmds:
      - mkdir -p bin/release
      - GOOS=linux GOARCH=amd64 go build -gcflags="all=-l -B -C" -ldflags="-s -w -X 'github.com/hanselrd/domino/internal/build.Version={{.BUILD_VERSION}}' -X 'github.com/hanselrd/domino/internal/build.Time={{.BUILD_TIME}}' -X 'github.com/hanselrd/domino/internal/build.Hash={{.BUILD_HASH}}'" -o bin/release/domino_linux_amd64 ./cmd/domino
  build-domino-windows-amd64-debug:
    cmds:
      - mkdir -p bin/debug
      - GOOS=windows GOARCH=amd64 go build -gcflags="all=-N -l" -ldflags="-X 'github.com/hanselrd/domino/internal/build.Version={{.BUILD_VERSION}}' -X 'github.com/hanselrd/domino/internal/build.Time={{.BUILD_TIME}}' -X 'github.com/hanselrd/domino/internal/build.Hash={{.BUILD_HASH}}'" -o bin/debug/domino_windows_amd64.exe ./cmd/domino
  build-domino-windows-amd64-release:
    cmds:
      - mkdir -p bin/release
      - GOOS=windows GOARCH=amd64 go build -gcflags="all=-l -B -C" -ldflags="-s -w -X 'github.com/hanselrd/domino/internal/build.Version={{.BUILD_VERSION}}' -X 'github.com/hanselrd/domino/internal/build.Time={{.BUILD_TIME}}' -X 'github.com/hanselrd/domino/internal/build.Hash={{.BUILD_HASH}}'" -o bin/release/domino_windows_amd64.exe ./cmd/domino
  build-release:
    deps:
      - build-domino-darwin-amd64-debug
      - build-domino-darwin-amd64-release
      - build-domino-darwin-arm64-debug
      - build-domino-darwin-arm64-release
      - build-domino-linux-amd64-debug
      - build-domino-linux-amd64-release
      - build-domino-windows-amd64-debug
      - build-domino-windows-amd64-release
  clean:
    cmds:
      - rm -rf bin
  default:
    deps:
      - build
  format:
    cmds:
      - goimports -w -local "github.com/hanselrd/domino" .
      - gofumpt -w -extra .
  test:
    cmds:
      - go test -gcflags="all=-N -l" -ldflags="" -v ./...
  update:
    cmds:
      - go get -u ./...
      - go mod tidy
      - go get gopkg.in/yaml.v3
