version: "3"
vars:
  BUILD_DIRTY:
    sh: git diff --quiet || echo "dirty"
  BUILD_HASH:
    sh: git rev-parse HEAD
  BUILD_SHORT_HASH:
    sh: git rev-parse --short=7 HEAD
  BUILD_TIME:
    sh: date --utc "+%Y-%m-%dT%H:%M:%SZ"
  BUILD_VERSION: 0.0.1-alpha.1
tasks:
  bootstrap:
    cmds:
      - go run build/taskfile.go
    sources:
      - build/taskfile.go
    generates:
      - Taskfile.yml
  build:
    deps:
      - build-debug
      - build-release
  build-debug:
    deps:
      - build-domino-darwin-amd64-debug
      - build-domino-darwin-arm64-debug
      - build-domino-debug
      - build-domino-linux-amd64-debug
      - build-domino-windows-amd64-debug
  build-domino-darwin-amd64-debug:
    cmds:
      - mkdir -p bin/debug
      - GOOS=darwin GOARCH=amd64 go build -gcflags="all=-N -l" -ldflags="-X 'github.com/hanselrd/domino/internal/build.Dirty={{.BUILD_DIRTY}}' -X 'github.com/hanselrd/domino/internal/build.Hash={{.BUILD_HASH}}' -X 'github.com/hanselrd/domino/internal/build.ShortHash={{.BUILD_SHORT_HASH}}' -X 'github.com/hanselrd/domino/internal/build.Time={{.BUILD_TIME}}' -X 'github.com/hanselrd/domino/internal/build.Version={{.BUILD_VERSION}}'" -o bin/debug/domino_darwin_amd64 ./cmd/domino
    sources:
      - cmd/**/*.go
      - internal/**/*.go
      - pkg/**/*.go
      - Taskfile.yml
    generates:
      - bin/debug/domino_darwin_amd64
    requires:
      vars:
        - BUILD_DIRTY
        - BUILD_HASH
        - BUILD_SHORT_HASH
        - BUILD_TIME
        - BUILD_VERSION
  build-domino-darwin-amd64-release:
    cmds:
      - mkdir -p bin/release
      - GOOS=darwin GOARCH=amd64 go build -gcflags="all=-l -B -C" -ldflags="-s -w -X 'github.com/hanselrd/domino/internal/build.Dirty={{.BUILD_DIRTY}}' -X 'github.com/hanselrd/domino/internal/build.Hash={{.BUILD_HASH}}' -X 'github.com/hanselrd/domino/internal/build.ShortHash={{.BUILD_SHORT_HASH}}' -X 'github.com/hanselrd/domino/internal/build.Time={{.BUILD_TIME}}' -X 'github.com/hanselrd/domino/internal/build.Version={{.BUILD_VERSION}}'" -o bin/release/domino_darwin_amd64 ./cmd/domino
    sources:
      - cmd/**/*.go
      - internal/**/*.go
      - pkg/**/*.go
      - Taskfile.yml
    generates:
      - bin/release/domino_darwin_amd64
    requires:
      vars:
        - BUILD_DIRTY
        - BUILD_HASH
        - BUILD_SHORT_HASH
        - BUILD_TIME
        - BUILD_VERSION
  build-domino-darwin-arm64-debug:
    cmds:
      - mkdir -p bin/debug
      - GOOS=darwin GOARCH=arm64 go build -gcflags="all=-N -l" -ldflags="-X 'github.com/hanselrd/domino/internal/build.Dirty={{.BUILD_DIRTY}}' -X 'github.com/hanselrd/domino/internal/build.Hash={{.BUILD_HASH}}' -X 'github.com/hanselrd/domino/internal/build.ShortHash={{.BUILD_SHORT_HASH}}' -X 'github.com/hanselrd/domino/internal/build.Time={{.BUILD_TIME}}' -X 'github.com/hanselrd/domino/internal/build.Version={{.BUILD_VERSION}}'" -o bin/debug/domino_darwin_arm64 ./cmd/domino
    sources:
      - cmd/**/*.go
      - internal/**/*.go
      - pkg/**/*.go
      - Taskfile.yml
    generates:
      - bin/debug/domino_darwin_arm64
    requires:
      vars:
        - BUILD_DIRTY
        - BUILD_HASH
        - BUILD_SHORT_HASH
        - BUILD_TIME
        - BUILD_VERSION
  build-domino-darwin-arm64-release:
    cmds:
      - mkdir -p bin/release
      - GOOS=darwin GOARCH=arm64 go build -gcflags="all=-l -B -C" -ldflags="-s -w -X 'github.com/hanselrd/domino/internal/build.Dirty={{.BUILD_DIRTY}}' -X 'github.com/hanselrd/domino/internal/build.Hash={{.BUILD_HASH}}' -X 'github.com/hanselrd/domino/internal/build.ShortHash={{.BUILD_SHORT_HASH}}' -X 'github.com/hanselrd/domino/internal/build.Time={{.BUILD_TIME}}' -X 'github.com/hanselrd/domino/internal/build.Version={{.BUILD_VERSION}}'" -o bin/release/domino_darwin_arm64 ./cmd/domino
    sources:
      - cmd/**/*.go
      - internal/**/*.go
      - pkg/**/*.go
      - Taskfile.yml
    generates:
      - bin/release/domino_darwin_arm64
    requires:
      vars:
        - BUILD_DIRTY
        - BUILD_HASH
        - BUILD_SHORT_HASH
        - BUILD_TIME
        - BUILD_VERSION
  build-domino-debug:
    cmds:
      - mkdir -p bin/debug
      - go build -gcflags="all=-N -l" -ldflags="-X 'github.com/hanselrd/domino/internal/build.Dirty={{.BUILD_DIRTY}}' -X 'github.com/hanselrd/domino/internal/build.Hash={{.BUILD_HASH}}' -X 'github.com/hanselrd/domino/internal/build.ShortHash={{.BUILD_SHORT_HASH}}' -X 'github.com/hanselrd/domino/internal/build.Time={{.BUILD_TIME}}' -X 'github.com/hanselrd/domino/internal/build.Version={{.BUILD_VERSION}}'" -o bin/debug/domino ./cmd/domino
    sources:
      - cmd/**/*.go
      - internal/**/*.go
      - pkg/**/*.go
      - Taskfile.yml
    generates:
      - bin/debug/domino
    requires:
      vars:
        - BUILD_DIRTY
        - BUILD_HASH
        - BUILD_SHORT_HASH
        - BUILD_TIME
        - BUILD_VERSION
  build-domino-linux-amd64-debug:
    cmds:
      - mkdir -p bin/debug
      - GOOS=linux GOARCH=amd64 go build -gcflags="all=-N -l" -ldflags="-X 'github.com/hanselrd/domino/internal/build.Dirty={{.BUILD_DIRTY}}' -X 'github.com/hanselrd/domino/internal/build.Hash={{.BUILD_HASH}}' -X 'github.com/hanselrd/domino/internal/build.ShortHash={{.BUILD_SHORT_HASH}}' -X 'github.com/hanselrd/domino/internal/build.Time={{.BUILD_TIME}}' -X 'github.com/hanselrd/domino/internal/build.Version={{.BUILD_VERSION}}'" -o bin/debug/domino_linux_amd64 ./cmd/domino
    sources:
      - cmd/**/*.go
      - internal/**/*.go
      - pkg/**/*.go
      - Taskfile.yml
    generates:
      - bin/debug/domino_linux_amd64
    requires:
      vars:
        - BUILD_DIRTY
        - BUILD_HASH
        - BUILD_SHORT_HASH
        - BUILD_TIME
        - BUILD_VERSION
  build-domino-linux-amd64-release:
    cmds:
      - mkdir -p bin/release
      - GOOS=linux GOARCH=amd64 go build -gcflags="all=-l -B -C" -ldflags="-s -w -X 'github.com/hanselrd/domino/internal/build.Dirty={{.BUILD_DIRTY}}' -X 'github.com/hanselrd/domino/internal/build.Hash={{.BUILD_HASH}}' -X 'github.com/hanselrd/domino/internal/build.ShortHash={{.BUILD_SHORT_HASH}}' -X 'github.com/hanselrd/domino/internal/build.Time={{.BUILD_TIME}}' -X 'github.com/hanselrd/domino/internal/build.Version={{.BUILD_VERSION}}'" -o bin/release/domino_linux_amd64 ./cmd/domino
    sources:
      - cmd/**/*.go
      - internal/**/*.go
      - pkg/**/*.go
      - Taskfile.yml
    generates:
      - bin/release/domino_linux_amd64
    requires:
      vars:
        - BUILD_DIRTY
        - BUILD_HASH
        - BUILD_SHORT_HASH
        - BUILD_TIME
        - BUILD_VERSION
  build-domino-release:
    cmds:
      - mkdir -p bin/release
      - go build -gcflags="all=-l -B -C" -ldflags="-s -w -X 'github.com/hanselrd/domino/internal/build.Dirty={{.BUILD_DIRTY}}' -X 'github.com/hanselrd/domino/internal/build.Hash={{.BUILD_HASH}}' -X 'github.com/hanselrd/domino/internal/build.ShortHash={{.BUILD_SHORT_HASH}}' -X 'github.com/hanselrd/domino/internal/build.Time={{.BUILD_TIME}}' -X 'github.com/hanselrd/domino/internal/build.Version={{.BUILD_VERSION}}'" -o bin/release/domino ./cmd/domino
    sources:
      - cmd/**/*.go
      - internal/**/*.go
      - pkg/**/*.go
      - Taskfile.yml
    generates:
      - bin/release/domino
    requires:
      vars:
        - BUILD_DIRTY
        - BUILD_HASH
        - BUILD_SHORT_HASH
        - BUILD_TIME
        - BUILD_VERSION
  build-domino-windows-amd64-debug:
    cmds:
      - mkdir -p bin/debug
      - GOOS=windows GOARCH=amd64 go build -gcflags="all=-N -l" -ldflags="-X 'github.com/hanselrd/domino/internal/build.Dirty={{.BUILD_DIRTY}}' -X 'github.com/hanselrd/domino/internal/build.Hash={{.BUILD_HASH}}' -X 'github.com/hanselrd/domino/internal/build.ShortHash={{.BUILD_SHORT_HASH}}' -X 'github.com/hanselrd/domino/internal/build.Time={{.BUILD_TIME}}' -X 'github.com/hanselrd/domino/internal/build.Version={{.BUILD_VERSION}}'" -o bin/debug/domino_windows_amd64.exe ./cmd/domino
    sources:
      - cmd/**/*.go
      - internal/**/*.go
      - pkg/**/*.go
      - Taskfile.yml
    generates:
      - bin/debug/domino_windows_amd64.exe
    requires:
      vars:
        - BUILD_DIRTY
        - BUILD_HASH
        - BUILD_SHORT_HASH
        - BUILD_TIME
        - BUILD_VERSION
  build-domino-windows-amd64-release:
    cmds:
      - mkdir -p bin/release
      - GOOS=windows GOARCH=amd64 go build -gcflags="all=-l -B -C" -ldflags="-s -w -X 'github.com/hanselrd/domino/internal/build.Dirty={{.BUILD_DIRTY}}' -X 'github.com/hanselrd/domino/internal/build.Hash={{.BUILD_HASH}}' -X 'github.com/hanselrd/domino/internal/build.ShortHash={{.BUILD_SHORT_HASH}}' -X 'github.com/hanselrd/domino/internal/build.Time={{.BUILD_TIME}}' -X 'github.com/hanselrd/domino/internal/build.Version={{.BUILD_VERSION}}'" -o bin/release/domino_windows_amd64.exe ./cmd/domino
    sources:
      - cmd/**/*.go
      - internal/**/*.go
      - pkg/**/*.go
      - Taskfile.yml
    generates:
      - bin/release/domino_windows_amd64.exe
    requires:
      vars:
        - BUILD_DIRTY
        - BUILD_HASH
        - BUILD_SHORT_HASH
        - BUILD_TIME
        - BUILD_VERSION
  build-release:
    deps:
      - build-domino-darwin-amd64-release
      - build-domino-darwin-arm64-release
      - build-domino-linux-amd64-release
      - build-domino-release
      - build-domino-windows-amd64-release
  clean:
    cmds:
      - rm -rf bin
  default:
    cmds:
      - task: format
      - task: bootstrap
      - task build
  format:
    cmds:
      - goimports -w -local "github.com/hanselrd/domino" .
      - gofumpt -w -extra .
      - golines -w -m 100 **/*.go
    sources:
      - '**/*.go'
  test:
    cmds:
      - go test -gcflags="all=-N -l" -ldflags="" -v ./...
  update:
    cmds:
      - go get -u ./...
      - go mod tidy
      - go get gopkg.in/yaml.v3
