version: "3"
tasks:
  bootstrap:
    deps:
      - update
    cmds:
      - go run build/taskfile.go
  build:
    deps:
      - build-debug
      - build-release
  build-debug:
    deps:
      - build-domino-darwin-amd64-debug
      - build-domino-darwin-amd64-release
      - build-domino-darwin-arm64-debug
      - build-domino-darwin-arm64-release
      - build-domino-linux-amd64-debug
      - build-domino-linux-amd64-release
      - build-domino-windows-amd64-debug
      - build-domino-windows-amd64-release
  build-domino-darwin-amd64-debug:
    cmds:
      - mkdir -p bin/debug
      - GOOS=darwin GOARCH=amd64 go build -gcflags="all=-N -l" -ldflags="" -o bin/debug/domino_darwin_amd64 ./cmd/domino
  build-domino-darwin-amd64-release:
    cmds:
      - mkdir -p bin/release
      - GOOS=darwin GOARCH=amd64 go build -gcflags="" -ldflags="-s -w" -o bin/release/domino_darwin_amd64 ./cmd/domino
  build-domino-darwin-arm64-debug:
    cmds:
      - mkdir -p bin/debug
      - GOOS=darwin GOARCH=arm64 go build -gcflags="all=-N -l" -ldflags="" -o bin/debug/domino_darwin_arm64 ./cmd/domino
  build-domino-darwin-arm64-release:
    cmds:
      - mkdir -p bin/release
      - GOOS=darwin GOARCH=arm64 go build -gcflags="" -ldflags="-s -w" -o bin/release/domino_darwin_arm64 ./cmd/domino
  build-domino-linux-amd64-debug:
    cmds:
      - mkdir -p bin/debug
      - GOOS=linux GOARCH=amd64 go build -gcflags="all=-N -l" -ldflags="" -o bin/debug/domino_linux_amd64 ./cmd/domino
  build-domino-linux-amd64-release:
    cmds:
      - mkdir -p bin/release
      - GOOS=linux GOARCH=amd64 go build -gcflags="" -ldflags="-s -w" -o bin/release/domino_linux_amd64 ./cmd/domino
  build-domino-windows-amd64-debug:
    cmds:
      - mkdir -p bin/debug
      - GOOS=windows GOARCH=amd64 go build -gcflags="all=-N -l" -ldflags="" -o bin/debug/domino_windows_amd64.exe ./cmd/domino
  build-domino-windows-amd64-release:
    cmds:
      - mkdir -p bin/release
      - GOOS=windows GOARCH=amd64 go build -gcflags="" -ldflags="-s -w" -o bin/release/domino_windows_amd64.exe ./cmd/domino
  build-release:
    deps:
      - build-domino-darwin-amd64-debug
      - build-domino-darwin-amd64-release
      - build-domino-darwin-arm64-debug
      - build-domino-darwin-arm64-release
      - build-domino-linux-amd64-debug
      - build-domino-linux-amd64-release
      - build-domino-windows-amd64-debug
      - build-domino-windows-amd64-release
  clean:
    cmds:
      - rm -rf bin
  format:
    cmds:
      - goimports -w -local "github.com/hanselrd/domino" .
  test:
    cmds:
      - go test -gcflags="all=-N -l" -ldflags="" -v ./...
  update:
    cmds:
      - go get -u ./...
      - go mod tidy
      - go get gopkg.in/yaml.v3
